#!/bin/bash
export copyright="2004 - $(date +%Y) Bellevue Linux. All Rights Reserved."

find . -type f -name "*.md" -exec bash -c 'lowdown \
    --template 'tools/html-template.lowdown' \
    -m "title=Bellevue Linux Users Group" \
    -m "css=/style.css" \
    -m "copyright=$copyright" \
    -m "lang=en-US" \
    -s \
    "$0" > "${0%.md}.html"' {} \;
